version: "3.9"

networks:
  test_net:
    driver: bridge

services:
  test_server:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/ocean
      - test_index_data:/index_data
    command: uvicorn oceandb.app:app --reload --workers 1 --host 0.0.0.0 --port 8000 --log-config log_config.yml
    environment:
      - OCEAN_DB_IMPL=clickhouse
      - CLICKHOUSE_HOST=test_clickhouse
      - CLICKHOUSE_PORT=8123
    ports:
      - ${OCEAN_PORT}:8000
    depends_on:
      - test_clickhouse
    networks:
      - test_net

  test_clickhouse:
    image: clickhouse/clickhouse-server:22.9-alpine
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      - CLICKHOUSE_TCP_PORT=9000
      - CLICKHOUSE_HTTP_PORT=8123
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - test_clickhouse_data:/bitnami/clickhouse
      - test_backups:/backups
      - ./config/backup_disk.xml:/etc/clickhouse-server/config.d/backup_disk.xml
      - ./config/ocean_users.xml:/etc/clickhouse-server/users.d/ocean.xml
    networks:
      - test_net

volumes:
  test_clickhouse_data:
    driver: local
  test_index_data:
    driver: local
  test_backups:
    driver: local
